### ISSUE TITLE
Does not respect provided `theme`

### ISSUE THREAD

**Issue by serhez** [Myzel394/jsonfly.nvim#11]
The plugin does not seem to respect the telescope theme provided in the command/config. I have tried providing the theme in the config

```lua
extensions = {
    jsonfly = {
	theme = "ivy",
	prompt_title = "JSON keys",
    },
}
```

as well as specifying it in the command

```lua
j = { "<cmd>Telescope jsonfly theme=ivy<cr>", "JSON keys" }
```

Is there any other way to do it I'm missing? Thank you! :)

**Comment by Myzel394** [comment]
Hey @serhez,

this should work now via specifying your theme in the command. I wasn't able to get it to work with specifying it in the config table unfortunately. However, I tried this setting on other extensions and none of them worked, so I guess it's some issues with telescope itself.

Nevertheless, you should be able to use it by using the aforementioned command variant :)

**Comment by serhez** [comment]
Thank you! 🙂
