### ISSUE TITLE
Copy path as jump action

### ISSUE THREAD

**Issue by guivazcabral** [Myzel394/jsonfly.nvim#6]
Hey! Super useful plugin to navigate json files, especially for the particular use case I have which is navigating through translation files. 

I have a suggestion though. It would be great to have the ability to copy the json path when selecting the key in telescope. I currently use https://github.com/phelipetls/jsonpath.nvim solely for that. 

Just a suggestion, feel free to close if you think it doesn't make sense. Thanks again!

**Comment by Myzel394** [comment]
> especially for the particular use case I have which is navigating through translation files.

Haha :D as a matter of fact, that was exactly what motivated me to create this plugin! :D

I tested out the plugin and it worked great! I don't think it makes sense to pretty much copy its behavior, when there's already a plugin for that available. I'll link it in the README so other people can see it!
